# Generated by Django 4.1.2 on 2022-11-03 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='profileimg',
            field=models.ImageField(blank=True, default='profile\\default-profile.png', null=True, upload_to='profile_pics'),
        ),
    ]
