# Generated by Django 4.1.2 on 2022-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_birthday_alter_account_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profileimg',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
    ]
