# Generated by Django 4.1.2 on 2022-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chat',
            field=models.IntegerField(null=True),
        ),
    ]
