# Generated by Django 4.1.2 on 2022-11-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
