# Generated by Django 4.1.2 on 2022-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='chat',
            field=models.IntegerField(default=0),
        ),
    ]
