# Generated by Django 4.1.2 on 2022-11-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
