# Generated by Django 4.1.2 on 2022-11-05 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='dead_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='room',
            name='meal_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='room',
            name='request_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('L', 'LGBTQ+'), ('A', 'Any')], max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
