# Generated by Django 4.1.2 on 2022-11-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_dead_time_room_meal_time_room_request_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_seat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='seat_count',
            field=models.IntegerField(default=1),
        ),
    ]
