# Generated by Django 4.1.2 on 2022-11-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_max_seat_room_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_seat',
            field=models.IntegerField(default=2),
        ),
    ]
