# Generated by Django 4.1.2 on 2022-11-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
    ]
