# Generated by Django 4.1.2 on 2022-11-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_max_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='Open', max_length=10),
        ),
    ]
