# Generated by Django 4.1.2 on 2022-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='hashtags',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
