# Generated by Django 4.1.2 on 2022-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_description_room_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hashtags',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
