# Generated by Django 4.1.2 on 2022-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_room_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hashtags',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
