# Generated by Django 4.1.2 on 2022-11-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_room_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hashtags',
            new_name='filter',
        ),
    ]
