# Generated by Django 4.1.2 on 2022-11-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_image'),
        ('chat', '0009_rename_hashtags_room_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
