# Generated by Django 4.1.2 on 2022-11-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='account',
        ),
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='gender',
            field=models.CharField(default='L', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
