# Generated by Django 4.1.2 on 2022-11-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_message_account_message_age_message_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='age',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
