# Generated by Django 4.1.2 on 2022-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_message_age_remove_message_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dead_time',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='room',
            name='meal_time',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
