# Generated by Django 4.1.2 on 2022-11-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_room_dead_time_alter_room_meal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='gender',
        ),
    ]
