# Generated by Django 4.1.2 on 2022-11-20 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_message_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=1000000),
        ),
    ]
