# Generated by Django 4.1.2 on 2022-11-11 15:25

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=30)),
                ('customer', models.CharField(max_length=30)),
                ('restaurant_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=300)),
                ('shopimg', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('chat_room', models.ManyToManyField(blank=True, to='shop.shopchat')),
            ],
        ),
    ]
