# Generated by Django 4.1.2 on 2022-11-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shop_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopchat',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
