# Generated by Django 4.1.2 on 2022-11-20 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopchat_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmessage',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=1000000),
        ),
    ]
