# Generated by Django 4.1.2 on 2022-11-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_shopchat_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopchat',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='shopchat',
            name='restaurant_name',
        ),
        migrations.AlterField(
            model_name='shopchat',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
