# Generated by Django 4.1.2 on 2022-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_addshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopchat',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
