# Generated by Django 4.1.2 on 2022-11-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopchat_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopchat',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
