# Generated by Django 4.1.2 on 2022-11-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopmessage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopchat',
            old_name='restaurant_name',
            new_name='restaurant_id',
        ),
    ]
