# Generated by Django 4.1.2 on 2022-11-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shopmessage_room_alter_shopmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='shopmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='shopmessage',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopchat'),
        ),
    ]
