# Generated by Django 4.1.2 on 2022-11-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ShopMessage',
        ),
    ]
