# Generated by Django 4.1.2 on 2022-11-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_message_shopmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
