# Generated by Django 4.1.2 on 2022-11-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_remove_shopmessage_room_remove_shopmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopchat',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
